baseURL = 'https://noahele.github.io/Blog'
languageCode = 'en'
title = "NoahELE's Blog"
theme = 'PaperMod'

enableRobotsTXT = true

[outputs]
home = ['HTML', 'RSS', 'JSON']

[params]
env = true
defaultTheme = 'auto'
showShareButtons = true
showReadingTime = true
showToc = true
showBreadCrumbs = true
showPostNavLinks = true
showCodeCopyButtons = true

[params.profileMode]
enabled = true


[[params.profileMode.buttons]]
name = 'Posts'
url = '/Blog/posts'

[[params.profileMode.buttons]]
name = 'Archives'
url = '/Blog/archives'

[[params.socialIcons]]
name = 'email'
url = 'mailto:noah.x.chen@outlook.com'

[[params.socialIcons]]
name = 'cv'
url = ''

[[params.socialIcons]]
name = 'github'
url = 'https://github.com/NoahELE'

[[params.socialIcons]]
name = 'rss'
url = '/Blog/index.xml'

[[menu.main]]
identifier = 'search'
name = 'Search'
url = '/search'
weight = 1

[[menu.main]]
identifier = 'archives'
name = 'Archives'
url = '/archives'
weight = 2

[[menu.main]]
identifier = 'posts'
name = 'Posts'
url = '/posts'
weight = 3
